[phases.setup]
nixPkgs = ["nodejs-20_x"]
aptPkgs = ["libatomic1", "build-essential"]

[phases.install]
dependsOn = ["setup"]
cmds = ["npm install"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "node server/index.js"

[phases.run]
cmds = ["node server/index.js"]